Rework
ysfchn/DynamicComponents-AI2 pull request #36
Opened 2020-12-21 23:49 UTC by StormiFire

### What is it?
This PR is to address some of the issues that users have experienced over the past month.
<hr>

### Review
#### Deprecations
Multiple functions were deprecated in favor of replacements that are either enhanced or have a new name that better fits the functionality. These will still be rendered (they will not be outlined in red), they will not break your project, but it is suggested you migrate to the new events and functions because some of the old ones may no longer return proper results!

- _ComponentCreated_: This was deprecated in favor of the new _ComponentBuilt_ event. It includes 1 extra parameter and gets called at a more accurate time than _ComponentCreated_ could be.
- _GetName_: This was deprecated in favor of the new _GetComponentMeta_ function. The key is named "type" from _GetComponentMeta_, not "name". **Projects can continue to use this as the appropriate response will continue to be returned! Take a look [here](https://user-images.githubusercontent.com/43486313/102832160-9b658880-43bb-11eb-88ed-3ab2a6f0d9cf.jpg) to view an example response.**
- _ListDetails_: This was deprecated in favor of the new _GetComponentMeta_, _GetEventMeta_, _GetFunctionMeta_, _GetPropertyMeta_ functions. **Projects should immediately migrate, this will return an empty string.**
- _RandomUUID_: This was deprecated in favor of the new _GenerateID_ function. **Projects can continue to use this as the appropriate response will continue to be returned!**
- _SchemaCreated_: This was deprecated in favor of the new _SchemaFinished_ event. All that's changed is 1 parameter being removed and one being added.

#### Behavioral changes of non-deprecations
- _ChangeId_: When replacing an ID, it will loop through **ALL** IDs and replace each one that contains the old ID! Even if the ID you're wanting to replace is "Timmy", but there are IDs like "Timmy-truck". To be clear again, only "Timmy" from "Timmy-truck" will be replaced, the "-truck" part will stay the same!
- _**Keys** using the Create function_: A new format is available, you can now use "%keyName" and it will also be replaced! Both "{keyName}" and "%keyName" will work.
- _LastUsedID_: Has reverted back to using _v2.0.0s_ method. If you delete a component with the last used ID, it will stay the same.
- _Thread_: _Async_ was replaced in favor of _Thread_, however it's only available from the Designer. You have 2 choices... "Main" and "UI". "UI" would be asynchronous creation and removal.
- _Remove_: Works asynchronously based on thread choice.

#### New functions
- _GetComponentMeta_, _GetEventMeta_, _GetFunctionMeta_, _GetPropertyMeta_: You can find an example of the responses [here](https://user-images.githubusercontent.com/43486313/102832160-9b658880-43bb-11eb-88ed-3ab2a6f0d9cf.jpg).
- _GetId_: Get a components ID by specifying the component.
- _GenerateID:_ Generate an ID to use when creating a component.

#### Internal
- Comments were removed, you are expected to look at the descriptions of blocks to understand their child functions.
- The _version_ was bumped to 8 and the _versionName_ was bumped to 3.0.0 because the _Async_ property was removed and likely will break some projects depending on the amount of times it was used. There were also many deprecations.

2020-12-23 14:31 UTC, ysfchn requested changes
Found these so far:

2020-12-23 14:31 UTC, ysfchn commented on src/com/yusufcihan/DynamicComponents/DynamicComponents.java
> +  helpUrl = "https://github.com/ysfchn/DynamicComponents-AI2/issues",
It would be nice to set this to the main repository link then add link a to README to go to the Issues if that's the case.

2020-12-23 14:31 UTC, ysfchn commented on src/com/yusufcihan/DynamicComponents/DynamicComponents.java
> +  }
I don't know how it will be useful to get the full schema after being created, because I think people will prefer comparing the schema names instead of comparing the full schema data.

2020-12-23 14:31 UTC, ysfchn commented on src/com/yusufcihan/DynamicComponents/DynamicComponents.java
> +package com.yusufcihan.dynamiccomponents;
Are you sure this won't break anything when upgrading the extension or during compiling the app?

2020-12-23 14:35 UTC, ysfchn commented
And I personally like having comments because it can be useful for future contributions, and people (including us) can understand after a long time 😅

2020-12-23 15:50 UTC, StormiFire commented on src/com/yusufcihan/DynamicComponents/DynamicComponents.java
> +package com.yusufcihan.dynamiccomponents;
I actually have experienced issues with this over the past view days. For me if I had run into issue, I simple reimported the extension again and it was fine, but I did change the package name back to what it was originally for what I'll commit later.

2020-12-23 15:51 UTC, StormiFire commented on src/com/yusufcihan/DynamicComponents/DynamicComponents.java
> +  helpUrl = "https://github.com/ysfchn/DynamicComponents-AI2/issues",
No problem!

2020-12-24 14:28 UTC, ysfchn approved these changes
LGTM, but I need to do some tests before merging. 😄

2020-12-26 13:47 UTC, StormiFire commented
Is your test done yet? Because it's passed December 24<sup>th</sup> which was the date I promised many people a fix.

2020-12-26 13:52 UTC, merged